### ISSUE TITLE
🚀 Add Support for YAML Input Files to CLI

### ISSUE THREAD

**Issue by Denish3436** [StackGuardian/tirith#196] opened 2024-10-06 11:43 UTC
The current CLI implementation only supports JSON input files for policy evaluation. It would be beneficial to add support for YAML files as an alternative input format, given YAML's readability and wide adoption.

This feature will require updating the input handling logic in the main function and potentially modifying the `start_policy_evaluation` function to parse YAML files correctly.

**Comment by refeed** [comment] 2024-10-22 12:20
Hi @Denish3436 thanks for submitting this issue! because there's already the same issue, I have to close this

Closing as duplicate of https://github.com/StackGuardian/tirith/issues/153

**Closed by refeed** 2024-10-22 12:20 UTC
Labels: enhancement
